name: Auto Update Stock Market

on:
  schedule:
    # 設定每 5 分鐘自動觸發一次
    - cron: '*/5 * * * *'
  workflow_dispatch: # 允許手動點擊按鈕觸發

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Stock Update Script
        run: node index.js
